### ISSUE TITLE
update Interval inverted

### ISSUE THREAD

**Issue by BenediktKeppner** [dfaust/plasma-applet-netspeed-widget#38] opened 2023-01-23 12:33 UTC
It occurs to me that in version 0.1.1 the update interval is inverted meaning that 1.0s results in 1s, but 0.5 in 2s and 2s results in 0.5s for example... 
Im not sure if this is really the case, but definitively i cant set it to slow update intervals like 3 or 5 seconds...

**Comment by dfaust** [comment] 2023-08-04 14:15
Are you sure you meant to file an issue with `plasma-applet-netspeed-widget` (`org.kde.netspeedWidget`)?

I don't think I ever released a version 0.1.1 and even if I did, it would be ancient.
Anyway, I just released version 2.0, with which I can't reproduce the issue.
I'll close this issue, please re-open it in case I'm mistaken.

**Closed as completed by dfaust** 2023-08-04 14:15 UTC
