### ISSUE TITLE
Aur build error.

### ISSUE THREAD

**Issue by roachsinai** [dfaust/plasma-applet-netspeed-widget#10] opened 2019-02-11 17:48 UTC
CMake Error: No source or binary directory provided

**Comment by andryNoor** [comment] 2019-02-11 19:30
yes, Kvantum also has this issue

https://github.com/tsujan/Kvantum/issues/344#issue-408926269

**Comment by dfaust** [comment] 2019-02-11 19:53
Thanks for the info.
What cmake version are you using? Version 3.13.2 works fine for me.
Also I use `plasma_install_package` (from plasma 5.14.5), so I don't know where I would even fix that issue.

**Comment by tsujan** [comment] 2019-02-12 00:32
@dfaust Since there was a link to Kvantum here:

I don't know about your project but in the case of mine (Kvantum), the problem was not in the source but in the lack of a build directory in AUR's PKGBUILD.

**Comment by roachsinai** [comment] 2019-02-12 02:08
I'm using Manjaro latest.

+ cmake: 3.13.3
+ DE: KDE 5.54.0 / Plasma 5.14.5

**Comment by tsujan** [comment] 2019-02-12 02:20
> I'm using Manjaro latest.

I have Manjaro Testing and cmake 3.13.4.

Anyhow, I checked the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-netspeed) for this project. As I'd suspected, it doesn't make a build directory before compilation and that's the cause of the problem.

All such PKGBUILDs should be fixed in AUR.

**Comment by dfaust** [comment] 2019-02-17 16:57
Thank you, @tsujan. That seems to be the problem, indeed.

So I suggest you notify the AUR package maintainer. I'll close this issue, since it's not a plasma-applet-netspeed-widget bug.

**Closed as completed by dfaust** 2019-02-17 16:57 UTC

**Comment by wget** [comment] 2019-04-28 22:19
@dfaust I'm the AUR maintainer. It is building fine on Arch Linux though.
