### ISSUE TITLE
on Kubuntu 22.04 / Plasma 5.24, it only shows 0 kB/s upload/download 

### ISSUE THREAD

**Issue by tchwpkgorg** [dfaust/plasma-applet-netspeed-widget#33] opened 2022-05-06 22:07 UTC
On Kubuntu 22.04 / Plasma 5.24, the widget only shows 0 kB/s upload/download.

It used to work fine with Kubuntu 21.10 and earlier.

**Comment by Rougnt** [comment] 2022-05-15 06:18
This widget need `ksysguard`. But I can not install it on Kubuntu 22.04

**Comment by srsgores** [comment] 2022-05-19 07:24
Yeah, this worked:

```bash
sudo apt install kysguard
```

Then make sure to reboot:

```bash
reboot
```

**Comment by psychoche** [comment] 2022-05-19 07:51
@srsgores You can't install `ksysguard`. There is no such package anymore.

**Comment by srsgores** [comment] 2022-05-19 18:33
It did work for me on KDE Neon.

**Comment by tchwpkgorg** [comment] 2022-06-01 21:15
There is no "ksysguard" package on Ubuntu 22.04.

I have these with "sysguard" in the name:

> 
> $ dpkg -l|grep sysguard
> ii  libkf5sysguard-bin                            4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        library for system monitoring - utilities
> ii  libkf5sysguard-data                           4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          all          library for system monitoring - data files
> ii  libksysguardformatter1                        4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        library for system monitoring - ksysguardformatter shared library
> ii  libksysguardsensorfaces1                      4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        library for system monitoring - ksysguardsensorfaces shared library
> ii  libksysguardsensors1                          4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        library for system monitoring - ksysguardsensors shared library
> ii  libksysguardsystemstats1                      4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        library for monitoring your system - system stats shared library
> ii  qml-module-org-kde-ksysguard                  4:5.24.5-0ubuntu1~ubuntu22.04~ppa1          amd64        KSysGuard QtDeclarative QML Support

**Comment by puyo** [comment] 2022-10-19 01:24
Same problem

**Comment by flwwater** [comment] 2022-11-27 00:57
Same problem on kubuntu22.04

**Comment by dfaust** [comment] 2022-12-12 08:26
I'm closing this as duplicate of #28.

**Closed as not planned by dfaust** 2022-12-12 08:26 UTC
